default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # You can replace this with the latest version
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]  # Ensure compatibility with Black

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: ["--in-place","--remove-unused-variables", "--remove-all-unused-imports"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.10
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        name: black
        language_version: python3.10
  # ------ TODO: re-add this -----
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.9 # Update me!
  #   hooks:
  #     - id: bandit
  #   args: ["-c", "pyproject.toml"]
  #   additional_dependencies: ["bandit[toml]"]
