[tool.poetry]
name = "fastanime"
version = "0.3.0"
description = "A fast and efficient GUI and CLI anime scrapper"
authors = ["Benex254 <benedictx855@gmail.com>"]
license = "UNLICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
kivy = "^2.3.0"
yt-dlp = "^2024.5.27"
ffpyplayer = "^4.5.1"
plyer = "^2.1.0"
fuzzywuzzy = "^0.18.0"
rich = "^13.7.1"
click = "^8.1.7"
python-levenshtein = "^0.25.1"
kivymd = {url = "https://github.com/kivymd/KivyMD/archive/master.zip"}

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
isort = "^5.13.2"
pytest = "^8.2.2"
ruff = "^0.4.10"

pre-commit = "^3.7.1"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
fastanime = 'fastanime:FastAnime'
